blogs/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = "blogs"

urlpatterns = [
    path("create/comment/", login_required(views.CreateComment.as_view()), name="create_comment"),
    path("create/reply/", login_required(views.CreateReply.as_view()), name="create_reply"),
    path("create/bookmark/", login_required(views.CreateBookmark.as_view()), name="create_bookmark"),
    path("create/like/", login_required(views.CreateLike.as_view()), name="create_like"),
    path("<slug:slug>/", views.BlogView.as_view(), name="blog"),
]

djcms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', include('home.urls')),
    
    path('blog/admin', admin.site.urls),

    path("blog/accounts", include("accounts.urls")),
    path("blog/blogs", include("blogs.urls")),
    path("blog/manage", include("management.urls")),

    path("blog", views.Index.as_view(), name="index"),
    path("blog/trendings", views.Trendings.as_view(), name="trendings"),
    path("blog/latest", views.Latest.as_view(), name="latest"),
    path("blog/popular", views.Popular.as_view(), name="popular"),
    path("blog/search", views.Search.as_view(), name="search"),
    path("blog/bookmark", views.BookmarkView.as_view(), name="bookmark"),
    path("blog/terms-and-conditions", views.TermsAndConditions.as_view(), name="terms_and_conditions"),
    path("blog/category", views.CategoryView.as_view(), name="category"),
    path("blog/category/<slug:cat>", views.GetCategory.as_view(), name="get_category"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('about', views.about, name='about'),
    path('basiccourse', views.basiccourse, name='basiccourse'),
    path('dataanalytics', views.dataanalytics, name='dataanalytics'),
    path('datascience', views.datascience, name='datascience'),
    path('contact', views.contact, name='contact'),
    path('courses', views.courses, name='courses'),

    
]

management/urls.py
from django.urls import path
from . import views

app_name = "manage"

urlpatterns = [
    path("blog/", views.ManageBlog.as_view(), name="blog"),
    path("category/", views.ManageCategory.as_view(), name="category"),
    path("comment/", views.ManageComment.as_view(), name="comment"),

    path("create/blog/", views.CreateBlog.as_view(), name="create_blog"),
    path("create/category/", views.CreateCategory.as_view(), name="create_category"),

    path("delete/blog/<int:id>/", views.DeleteBlog.as_view(), name="delete_blog"),
    path("delete/category/<int:id>", views.DeleteCategory.as_view(), name="delete_category"),
    path("delete/comment/<int:id>", views.DeleteComment.as_view(), name="delete_comment"),

    path("edit/blog/<int:id>/", views.EditBlog.as_view(), name="edit_blog"),
    path("edit/category/<int:id>", views.EditCategory.as_view(), name="edit_category"),
]

blogs/models.py
from django.db import models
from accounts.models import User
from django.utils.text import slugify
from ckeditor.fields import RichTextField

# Create your models here.
class Category(models.Model):
    category = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(default="", max_length=30)
    desc = models.TextField()
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.category)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.category
    
class Blog(models.Model):
    slug = models.SlugField(unique=True, null=False, blank=False, max_length=100)
    title = models.CharField(max_length=100)
    desc = models.TextField()
    content = RichTextField()
    thumbnail = models.ImageField(upload_to="thumbnails/%Y/%m/%d/")
    views = models.IntegerField(default=0)
    categories = models.ManyToManyField(Category, related_name="blogs")
    is_active = models.BooleanField(default=True)
    is_published = models.BooleanField(default=True)
    published_on = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(to=User, on_delete=models.SET_NULL, related_name="blogs", null=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Blog, self).save(*args, **kwargs)

class Comment(models.Model):
    comment = models.TextField()
    likes = models.IntegerField(default=0)
    blog = models.ForeignKey(to=Blog, on_delete=models.SET_NULL, related_name="comments", null=True)
    creator = models.ForeignKey(to=User, on_delete=models.SET_NULL, related_name="comments", null=True)
    published_on = models.DateField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.comment

class Reply(models.Model):
    reply = models.TextField()
    likes = models.IntegerField(default=0)
    comment = models.ForeignKey(to=Comment, on_delete=models.SET_NULL, related_name="replies", null=True, blank=True)
    creator = models.ForeignKey(to=User, on_delete=models.SET_NULL, related_name="replies", null=True)
    published_on = models.DateField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.reply

class Bookmark(models.Model):
    blog = models.ForeignKey(to=Blog, on_delete=models.SET_NULL, related_name="bookmarks", null=True, blank=True)
    creator = models.ForeignKey(to=User, on_delete=models.SET_NULL, related_name="bookmarks", null=True, blank=True)
    created_on = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"Bookmark({self.id}, {self.creater.username})"

class BlogLike(models.Model):
    blog = models.ForeignKey(to=Blog, on_delete=models.SET_NULL, related_name="likes", null=True, blank=True)
    creator = models.ForeignKey(to=User, on_delete=models.SET_NULL, related_name="likes", null=True, blank=True)

    def __str__(self):
        return f"BlogLike({self.id}, {self.creator.username})"

management/models.py
from django.db import models

# Create your models here.

management/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget

class CKEditorForm(forms.Form):
    content = forms.CharField(widget = CKEditorWidget())

blogs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.views import View
from django.db.models import F
from django.urls import reverse
from .models import *

# Create your views here.
def get_blog_url(slug):
    return reverse("blogs:blog", args=[slug])

class BlogView(View):
    def get(self, request, slug):
        queryset = Blog.objects.filter(is_active=True, slug=slug)
        blog = get_object_or_404(queryset)
        blog.views = F("views") + 1
        blog.save()
        blog.refresh_from_db()

        context = {
            "blog": blog,
            "comments": blog.comments.filter(is_active=True)
        }
        if request.user.is_authenticated:
            context["bookmarked"] = Bookmark.objects.filter(creator=request.user, blog=blog).first()
            context["liked"] = BlogLike.objects.filter(blog=blog, creator=request.user).first()

        return render(request, "blogs/blog.html", context)

class CreateComment(View):
    def post(self, request):
        blog = get_object_or_404(Blog.objects.filter(is_active=True, id=request.POST.get("id")))
        comment = request.POST.get("comment")
        if not comment:
            messages.warning(request, "Comment required")
            return redirect("blogs:blog", slug=blog.slug)
        c = Comment(
            comment = comment,
            creator = request.user,
            blog = blog
        )
        c.save()
        messages.success(request, "Comment created")
        return redirect(get_blog_url(blog.slug)+"#comments")

class CreateReply(View):
    def post(self, request):
        comment = get_object_or_404(Comment.objects.filter(is_active=True, id=request.POST.get("id")))
        reply = request.POST.get("reply")
        if not reply:
            messages.warning(request, "Reply required")
            return redirect("blogs:blog", slug=comment.blog.slug)

        r = Reply(
            reply = request.POST.get("reply", ""),
            comment = comment,
            creator = request.user
        )
        r.save()

        messages.success(request, "Reply created")
        return redirect(get_blog_url(comment.blog.slug)+"#comments")

class CreateBookmark(View):
    def post(self, request):
        blog = get_object_or_404(Blog.objects.filter(is_active=True, id=request.POST.get("id")))
        bookmarked = Bookmark.objects.filter(creator=request.user, blog=blog).first()
        if bookmarked:
            messages.info(request, "Already bookmarked this blog")
        else:
            b = Bookmark(
                blog = blog,
                creator = request.user
            )
            b.save()
            messages.success(request, "Bookmark created")
        return redirect("blogs:blog", slug=blog.slug)

class CreateLike(View):
    def post(self, request):
        blog = get_object_or_404(Blog.objects.filter(is_active=True, id=request.POST.get("id")))
        liked = BlogLike.objects.filter(blog=blog, creator=request.user).first()
        if liked:
            messages.info(request, "You are already liked this post")
        else:
            l = BlogLike(creator=request.user, blog=blog)
            l.save()
            messages.success(request, "Liked this blog")
        return redirect(get_blog_url(blog.slug)+"#features")

management/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.views import View
from blogs.models import Category, Blog, Comment
from django.utils import timezone
from .forms import CKEditorForm

# Create your views here.
class ManageBlog(View):
    def get(self, request):
        blogs = Blog.objects.filter(is_active=True, creator=request.user)
        return render(request, "management/blog.html", {"blogs": blogs})

class ManageCategory(View):
    def get(self, request):
        categories = Category.objects.filter(is_active=True)
        return render(request, "management/category.html", {"categories": categories})


class CreateBlog(View):
    def get(self, request):
        form = CKEditorForm()
        categories = Category.objects.filter(is_active=True)
        return render(request, "management/create_blog.html", {"form": form, "categories": categories})

    def post(self, request):
        data = request.POST
        title = data.get("title")
        desc = data.get("desc")
        content = data.get("content")
        thumbnail = request.FILES.get("thumbnail")
        categories = data.getlist("categories") 
        status = data.get("status")

        if not (title and desc and content and thumbnail and categories and status):
            messages.info(request, "title, desc, content, thumbnail, categories, or status can't be empty")
            return redirect("manage:create_blog")

        try:
            status = bool(int(status))
        except:
            messages.info(request, "Something wrong with status")
            return redirect("manage:create_blog")

        blog = Blog(
            title = title,
            desc = desc,
            content = content,
            creator = request.user,
            thumbnail = thumbnail,
            is_published = status
        )
        blog.save()
        for id in categories:
            try:
                c = Category.objects.get(id=int(id))
                blog.categories.add(c)
            except Exception as e:
                pass

        blog.save()
        messages.success(request, "Blog created")

        return redirect("manage:create_blog")


class CreateCategory(View):
    def get(self, request):
        return render(request, "management/create_category.html")

    def post(self, request):
        data = request.POST
        category = data.get("category")
        desc = data.get("desc")

        c = Category.objects.filter(category=category).first()
        if c is not None:
            messages.warning(request, "Category already exists")
        else:
            c = Category(
                category=category,
                desc=desc
            )
            c.save()
            messages.success(request, "Category created")
        return redirect("manage:create_category")
        
class EditBlog(View):
    def get(self, request, id):
        blog = Blog.objects.filter(id=id, creator=request.user).first()
        if blog is None:
            messages.info(request, "Blog not exists")
            return redirect("manage:blog")
        categories = Category.objects.all()
        form = CKEditorForm({"content": blog.content})
        return render(request, "management/edit_blog.html", {"blog": blog, "categories": categories, "form": form})
    
    def post(self, request, id = None):
        data = request.POST
        id = data.get("id")
        blog = Blog.objects.filter(is_active=True, creator=request.user, id=id).first()
        if blog is None:
            messages.info(request, "Blog doesn't exists")
            return redirect("manage:blog")

        title = data.get("title")
        desc = data.get("desc")
        content = data.get("content")
        status = data.get("status")
        thumbnail = request.FILES.get("thumbnail")
        categories = data.getlist("categories")

        blog.title = title
        blog.desc = desc
        blog.content = content
        if thumbnail:
            blog.thumbnail = thumbnail

        try:
            status = int(status)
            if not blog.is_published and status:
                blog.published_on = timezone.now()
            blog.is_published = bool(status)
        except:
            messages.info(request, "Error while updating status")
        
        blog.categories.set([])
        for id in categories:
            try:
                c = Category.objects.get(id=int(id))
                blog.categories.add(c)
            except Exception as e:
                pass

        blog.save()
        messages.success(request, "Changes saved")

        return redirect("manage:blog")

class DeleteBlog(View):
    def get(self, request, id):
        blog = Blog.objects.filter(id=id, creator=request.user).first()
        if blog is None:
            messages.warning(request, "Blog doesn't exists")
        else:
            blog.is_active = False
            blog.save()
            messages.info(request, "Blog deleted")

        return redirect("manage:blog")

class EditCategory(View):
    def get(self, request, id):
        category = get_object_or_404(Category, id=id, is_active=True)
        return render(request, "management/edit_category.html", {"category": category})

    def post(self, request, id):
        c = Category.objects.filter(id=id, is_active=True).first()
        data = request.POST
        category, desc = data.get("category"), data.get("desc")
        if not ((category and desc) or c):
            messages.warning(request, "Category or Desc can't be empty. OR Category doesn't exists")
            return redirect("manage:category")
        c.category = category
        c.desc = desc
        c.save()
        messages.success(request, "Changes saved")
        return redirect("manage:category")
        

class DeleteCategory(View):
    def get(self, request, id):
        category = get_object_or_404(Category, id=id)
        category.is_active = False
        category.save()
        messages.info(request, "Category removed")
        return redirect("manage:category")

class ManageComment(View):
    def get(self, request):
        comments = Comment.objects.filter(is_active=True, blog__in=Blog.objects.filter(creator=request.user))
        return render(request, "management/comment.html", {"comments": comments})

class DeleteComment(View):
    def get(self, request, id):
        comment = get_object_or_404(Comment.objects.filter(id=id, is_active=True))
        if comment.blog.creator.username != request.user.username:
            messages.warning(request, "You are not author of that blog")
            return redirect("manage:comment")
        comment.is_active = False
        comment.save()
        messages.success(request, "Comment deleted")
        return redirect("manage:comment")

management/templates/management/blog.html
{% extends 'layout.html' %}

{% block title %}Manage{% endblock %}

{% block body %}
<div class="container table-responsive">
  <div class="row mb-3">
    <h1 class="text-center mb-3 mt-3">
      Manage Blogs
    </h1>
  </div>
  <a role="button" class="btn btn-secondary btn-sm round-btn" href="{% url 'manage:create_blog' %}">
    <i class="bi bi-plus-lg"></i>
    Create Blog
  </a>
  <div class="row">
    {% include 'management/blog_table.html' with blogs=blogs %}
  </div>
</div>
{% endblock %}

management/templates/management/blog_table.html
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">ID</th>
      <th scope="col">Title</th>
      <th scope="col">Desc</th>
      <th scope="col">Categories</th>
      <th scope="col">Created On</th>
      <th scope="col">Is Published</th>
      <th scope="col">Actions</td>
    </tr>
  </thead>
  <tbody class="table-group-divider">
    {% for blog in blogs %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <th>{{ blog.id }}</th>
      <td>{{ blog.title|truncatechars:30 }}</td>
      <td>{{ blog.desc|truncatechars:50 }}</td>
      <td>[{{ blog.categories.all|join:", " }}]</td>
      <td>{{ blog.published_on }}</td>
      <td>{% if blog.is_published %}Yes{% else %}No{% endif %}</td>
      <td>
        <a class="btn btn-warning" href="{% url 'manage:edit_blog' blog.id %}" role="button">
          <i class="bi bi-pencil-square"></i>
          Edit
        </a>
        <a class="btn btn-danger" href="{% url 'manage:delete_blog' blog.id %}" role="button">
          <i class="bi bi-trash3"></i>
          Delete
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

management/templates/management/category.html
{% extends 'layout.html' %}

{% block titlw %}Category{% endblock %}

{% block body %}
<div class="container mt-5">
  <div class="row mb-3">
    <h1 class="text-center">
      Manage Categories
    </h1>
  </div>
  <a role="button" class="btn btn-secondary btn-sm round-btn" href='{% url 'manage:create_category' %}'>
    <i class="bi bi-plus-lg"></i>
    Create Category
  </a>
  <div class="row">
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">ID</th>
          <th scope="col">Category</th>
          <th scope="col">Desc</th>
          <th scope="col">Actions</td>
        </tr>
      </thead>
      <tbody class="table-group-divider">
        {% for category in categories %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <th>{{ category.id }}</th>
          <td>{{ category.category|truncatechars:30 }}</td>
          <td>{{ category.desc|truncatechars:50 }}</td>
          <td>
            <a class="btn btn-warning" href="{% url 'manage:edit_category' category.id %}" role="button">
              <i class="bi bi-pencil-square"></i>
              Edit
            </a>
            <a class="btn btn-danger" href="{% url 'manage:delete_category' category.id %}" role="button">
              <i class="bi bi-trash3"></i>
              Delete
            </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

management/templates/management/comment.html
{% extends 'layout.html' %}

{% block titlw %}comment{% endblock %}

{% block body %}
<div class="container mt-5">
  <div class="row mb-3">
    <h1 class="text-center">
      Manage Comments
    </h1>
  </div>
  <div class="row">
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">ID</th>
          <th scope="col">Comment</th>
          <th scope="col">Creator</th>
          <th scope="col">Blog ID</th>
          <th scope="col">Blog Title</td>
          <th scope="col">Actions</td>
        </tr>
      </thead>
      <tbody class="table-group-divider">
        {% for comment in comments %}
        <tr>
          <td scope="row">{{ forloop.counter }}</td>
          <td>{{ comment.id }}</td>
          <td>{{ comment.comment|truncatechars:30 }}</td>
          <td>{{ comment.creator.username }}</td>
          <td>{{ comment.blog.id }}</td>
          <td>{{ comment.blog.title|truncatechars:30 }}</td>
          <td>
            <a class="btn btn-danger" href="{% url 'manage:delete_comment' comment.id %}" role="button">
              <i class="bi bi-trash3"></i>
              Delete
            </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

management/templates/management/create_blog.html
{% extends 'layout.html' %}

{% block title %}Add Blog{% endblock %}

{% block body %}
<div class="container mt-5 mb-5">
  <form method="post" action="{% url 'manage:create_blog' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <h1 class="text-center mb-3">
      Add Blog
    </h1>
    <div class="mb-3">
      <label for="title" class="form-label">Title:</label>
      <input type="text" class="form-control" id="title" placeholder="Title" name="title" required autofocus>
    </div>
    <div class="mb-3">
      <label for="desc" class="form-label">Description:</label>
      <textarea class="form-control" placeholder="Type description here" id="desc" style="height: 100px" name="desc"></textarea>
    </div>
    <br>
    {{ form.media }}
    {{ form.as_p }}
    <div class="mb-3">
      <label for="thumbnail" class="form-label">Thumbnail:</label>
      <input class="form-control" type="file" id="thumbnail" name="thumbnail" accept="image/*" required>
    </div>
    <div class="mb-3">
      <label for="categories" class="form-label">Categories:</label>
      <select id="categories" class="form-select" multiple aria-label="multiple select example" name="categories" required>
        <option disabled value=''>Select categories</option>
        {% for category in categories %}
        <option value="{{ category.id }}">{{ category.category }}</option>
        {% endfor %}
      </select>
      <small>Not have category? <a class="text-decoration-none" href="{% url 'manage:create_category' %}">Create</a></small>
    </div>
    <br>
    <div class="row">
      <div class="col-4">
        <p>Status:</p>
      </div>
      <div class="form-check col-4">
        <input class="form-check-input" type="radio" name="status" value="0" id="draft">
        <label class="form-check-label" for="draft">Draft</label>
      </div>
      <div class="form-check col-4">
        <input class="form-check-input" type="radio" name="status" value="1" id="publish" checked="checked">
        <label class="form-check-label" for="publish">Publish</label>
      </div>
    </div>
    <div class="row float-end">
      <button type="submit" class="btn btn-outline-success" style="background-color: #59bd79;"><b>Publish</b></button>
    </div>
  </form>
</div>
{% endblock %}

management/templates/management/create_category.html
{% extends 'layout.html' %}

{% block title %}Add Category{% endblock %}

{% block body %}
<div class="container mt-5 mb-5">
  <form method="post" action="{% url 'manage:create_category' %}">
    {% csrf_token %}
    <h1 class="text-center mb-3">
      Add Category
    </h1>
    <div class="mb-3">
      <label for="category" class="form-label">Category:</label>
      <input type="text" class="form-control" id="category" placeholder="category" name="category">
    </div>
    <div class="mb-3">
      <label for="desc" class="form-label">Description:</label>
      <textarea class="form-control" id="desc" rows="5" name="desc" placeholder="Type description here"></textarea>
    </div>
    <div class="row float-end">
      <button type="submit" class="btn btn-outline-success" style="background-color: #59bd79;">Create</button>
    </div>
  </form>
</div>
{% endblock %}

management/templates/management/edit_blog.html
{% extends 'layout.html' %}

{% block title %}Add Blog{% endblock %}

{% block body %}
<div class="container mt-5">
  <div class="row mb-3">
    <h1 class="text-center">
      Edit Blog
    </h1>
  </div>
  <div class="row">
    <form method="post" action="{% url 'manage:edit_blog' blog.id %}" enctype="multipart/form-data">
      {% csrf_token %}
      <input type="hidden" name="id" value="{{ blog.id }}">
      <div class="row mb-3">
        <label for="title" class="form-label">Title:</label>
        <input type="text" class="form-control" id="title" placeholder="Title" name="title" value="{{ blog.title }}" required autofocus>
      </div>
      <div class="row mb-3">
        <label for="desc" class="form-label">Description:</label>
        <textarea class="form-control" placeholder="Type description here" id="desc" style="height: 100px" name="desc">{{ blog.desc }}</textarea>
      </div>
      <br>
      {{ form.media }}
      {{ form.as_p }}
      <div class="row mb-3">
        <label for="thumbnail" class="form-label">Thumbnail:</label>
        <input class="form-control" type="file" id="thumbnail" name="thumbnail" accept="image/*">
        <small>Current: <a class="text-decoration-none" href="{{ blog.thumbnail.url }}">{{ blog.thumbnail.url }}</a></small>
      </div>
      <div class="row mb-3">
        <label for="categories" class="form-label">Categories:</label>
        <select id="categories" class="form-select" multiple aria-label="multiple select example" name="categories" required>
          <option disabled value=''>Select categories</option>
          {% for category in categories %}
          <option value="{{ category.id }}" {% if category in blog.categories.all %}selected{% endif %}>{{ category.category }}</option>
          {% endfor %}
        </select>
        <small>Not have category? <a class="text-decoration-none" href="{% url 'manage:create_category' %}">Create</a></small>
      </div>
      <br>
      <div class="row">
        <div class="col-4">
          <p>Status:</p>
        </div>
        <div class="form-check col-4">
          <input class="form-check-input" type="radio" name="status" value="0" id="draft" {% if not blog.is_published %}checked="checked"{% endif %}>
          <label class="form-check-label" for="draft">Draft</label>
        </div>
        <div class="form-check col-4">
          <input class="form-check-input" type="radio" name="status" value="1" id="publish" {% if blog.is_published %}checked="checked"{% endif %}>
          <label class="form-check-label" for="publish">Publish</label>
        </div>
      </div>
      <div class="row float-end">
        <button type="submit" class="btn btn-outline-success" style="background-color: #59bd79;">Publish</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

management/templates/management/edit_category.html
{% extends 'layout.html' %}

{% block title %}Edit Category{% endblock %}

{% block body %}
<div class="container mt-5 mb-5">
  <div class="row">
    <h1 class="text-center mb-3">
      Edit Category
    </h1>
  </div>
  <div class="row">
    <form method="post" action="{% url 'manage:edit_category' category.id %}">
      {% csrf_token %}
      <div class="row mb-3">
        <label for="category" class="form-label">Category:</label>
        <input type="text" class="form-control" id="category" placeholder="Category" name="category" value="{{ category.category }}" required autofocus>
      </div>
      <div class="row mb-3">
        <label for="desc" class="form-label">Description:</label>
        <textarea class="form-control" placeholder="Type description here" id="desc" style="height: 100px" name="desc">{{ category.desc }}</textarea>
      </div>
      <div class="row float-end">
        <button type="submit" class="btn btn-outline-success" style="background-color: #59bd79;">Save</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}