blogs/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = "blogs"

urlpatterns = [
    path("create/comment/", login_required(views.CreateComment.as_view()), name="create_comment"),
    path("create/reply/", login_required(views.CreateReply.as_view()), name="create_reply"),
    path("create/bookmark/", login_required(views.CreateBookmark.as_view()), name="create_bookmark"),
    path("create/like/", login_required(views.CreateLike.as_view()), name="create_like"),
    path("<slug:slug>/", views.BlogView.as_view(), name="blog"),
]

djcms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', include('home.urls')),
    
    path('blog/admin', admin.site.urls),

    path("blog/accounts", include("accounts.urls")),
    path("blog/blogs", include("blogs.urls")),
    path("blog/manage", include("management.urls")),

    path("blog", views.Index.as_view(), name="index"),
    path("blog/trendings", views.Trendings.as_view(), name="trendings"),
    path("blog/latest", views.Latest.as_view(), name="latest"),
    path("blog/popular", views.Popular.as_view(), name="popular"),
    path("blog/search", views.Search.as_view(), name="search"),
    path("blog/bookmark", views.BookmarkView.as_view(), name="bookmark"),
    path("blog/terms-and-conditions", views.TermsAndConditions.as_view(), name="terms_and_conditions"),
    path("blog/category", views.CategoryView.as_view(), name="category"),
    path("blog/category/<slug:cat>", views.GetCategory.as_view(), name="get_category"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('about', views.about, name='about'),
    path('basiccourse', views.basiccourse, name='basiccourse'),
    path('dataanalytics', views.dataanalytics, name='dataanalytics'),
    path('datascience', views.datascience, name='datascience'),
    path('contact', views.contact, name='contact'),
    path('courses', views.courses, name='courses'),

    
]

templates/bookmark.html
{% extends 'layout.html' %}

{% block title %}Закладки{% endblock %}

{% block body %}
<div class="container mt-5 mb-5">
  <div class="row">
    <h1 class="text-center mt-3 mb-3">
      Закладки
    </h1>
  </div>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for bookmark in bookmarks %}
      {% if bookmark.blog.is_active %}
        {% include 'card.html' with blog=bookmark.blog %}
      {% endif %}
    {% empty %}
      </div>
      <div class="row mt-5">
        <p class="text-center">
          Пока не добавил ни один блог в закладки!!!
        </p>
    {% endfor %}
  </div>
  {% include 'pagination.html' with blogs=bookmarks %}
</div>
{% endblock %}

templates/card.html
<section class="section courses" id="courses" style="margin-top: 0;">
  <div class="container">
    <div class="row"></div>
    <div class="row event_box">
        <div class="events_item">
          <div class="thumb">
            <a href="{% url 'blogs:blog' blog.slug %}">
              <img src="{{ blog.thumbnail.url }}" class="card-img-top" alt="blog's thumbnail">
            </a>
          </div>
          <div class="down-content">
            <a href="{% url 'blogs:blog' blog.slug %}"><h4 class="blog-title">{{ blog.title }}</h4></a>
            <span>{{ blog.desc|truncatechars:100 }}</span>
          </div>
          <div class="row justify-content-evenly mb-1">
            <div class="col-4">
              <p class="text-muted float-start">
                <i class="bi bi-eye"></i>
                {{ blog.views }}
              </p>
            </div>
            <div class="col-6">
              <p class="text-muted float-end">
                <i class="bi bi-clock-history"></i>
                {{ blog.published_on|timesince }}
              </p>
            </div>
          </div>
        </div>
      </div>
  </div>
</section>


<!--
<div class="col">
  <div class="card h-100">
    <div class="image-container">
      <img src="{{ blog.thumbnail.url }}" class="card-img-top" alt="blog's thumbnail">
    </div>
    <div class="card-body">
      <h5 class="card-title">{{ blog.title }}</h5>
      <p class="card-text">{{ blog.desc|truncatechars:100 }}</p>
    </div>
    <div class="row justify-content-evenly mb-1">
      <div class="col-4">
        <p class="text-muted float-start">
          <i class="bi bi-eye"></i>
          {{ blog.views }}
        </p>
      </div>
      <div class="col-6">
        <p class="text-muted float-end">
          <i class="bi bi-clock-history"></i>
          {{ blog.published_on|timesince }}
        </p>
      </div>
    </div>
    <a class="btn custom-btn w-100" href="{% url 'blogs:blog' blog.slug %}" role="button">Читать далее -></a>
<style>
  .custom-btn {
  color: #59bd79;
  border-color: #59bd79;
  background-color: transparent;
  border-radius: 0.25rem; /* Углы кнопки */
  transition: all 0.3s ease; /* Плавный переход при наведении */
}

.custom-btn:hover {
  color: #ffffff;
  background-color: #59bd79;
  border-color: #59bd79;
}

</style>
  </div>
</div>
-->

templates/category.html
{% extends 'layout.html' %}

{% block title %}Последний{% endblock %}

{% block body %}
{% endblock %}

templates/get_category.html
{% extends 'layout.html' %}

{% block title %}Последний{% endblock %}

{% block body %}
<div class="container mt-5 mb-5">
  <div class="row mb-5">
    <h2 class="text-center">{{ category.category }}</h2>
    <p>{{ category.desc }}</p>
  </div>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for blog in category.blogs.all %}
      {% if blog.is_active %}
        {% include "card.html" with blog=blog %}
      {% endif %}
    {% empty %}
      <p class="text-center">Блог не найден!!!</p>
    {% endfor %}
  </div>
</div>
{% endblock %}

templates/index.html
{% extends 'layout.html' %}

{% block title %}Блог{% endblock %}

{% block body %}
<div class="container" style="margin-top: 80px; margin-bottom: 50px;">
  <div class="row mb-1">
    <h2 style="text-align: center;"><b>Недавние Посты</b></h2>
    <div class="col-6">



    </div>
    <div class="col-6">
      <a class="btn btn-primary float-end" href="{% url 'latest' %}" role="button">
        <i class="bi bi-list-check"></i>
        Посмотреть все
      </a>
    </div>
  </div>
  <div class="row row-cols-1 row-cols-md-3 g-4" style="margin-top: 20px;">
    {% for blog in latest %}
      {% include 'card.html' with blog=blog %}
    {% endfor %}
  </div>

  <br><hr>

</div>
{% endblock %}

templates/latest.html
{% extends 'layout.html' %}

{% block title %}Latest{% endblock %}

{% block body %}
<div class="container" style="margin-top: 100px;">
  <div class="row mb-1">
    <h2 style="text-align: center;"><b>Недавние Посты</b></h2>
    <div class="col-6">



    </div>

  </div>
  <div class="row row-cols-1 row-cols-md-3 g-4 mt-1">
    {% for blog in blogs %}
      {% include 'card.html' with blog=blog %}
    {% endfor %}
  </div>
  {% include 'pagination.html' with blogs=blogs %}
</div>
{% endblock %}

templates/layoutaia.html
<!DOCTYPE html>
<html lang="en-US">
<head>
  {% load static %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta property="og:title" content="{% block ogtitle %}AI Academy Tajikistan{% endblock %}">
  <meta property="og:image" itemprop="image" content="{{ SITE_URL }}{% block ogimage %}{% static 'img/og.png' %}{% endblock %}">
  <meta property="og:description" content="{% block ogdescription %}Академия ИИ в Республике Таджикистан является первым образовательным учреждением, специализирующимся на искусственном интеллекте в стране. Основа видения ИИ в Таджикистане была заложена по программе Университета Стенфорда и на магистерской работе Университета Гарварда основателем zypl.ai, НПО “ТаджРапт” и Академии ИИ - Азизджоном Азими.{% endblock %}">
  
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">

  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>Академия ИИ</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.png' %}">

	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}" type="text/css" media="all">
	<link rel="stylesheet" href="{% static 'css/all.min.css'%}" type="text/css" media="all">
	<link rel="stylesheet" href="{% static 'css/slick.css'%}" type="text/css" media="all">
	<link rel="stylesheet" href="{% static 'css/simple-line-icons.css'%}" type="text/css" media="all">
	<link rel="stylesheet" href="{% static 'css/style.css'%}" type="text/css" media="all">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">

</head>

</head>

<body>


  <!-- site wrapper -->
<div class="site-wrapper">

	<div class="main-overlay"></div>

	<!-- header -->
	<header class="header-classic">

			<div class="container-xl">
				<!-- header top -->
				<div class="header-top">
					<div class="row align-items-center">

						<div class="col-md-4 col-xs-12">
							<!-- site logo -->
							<a class="navbar-brand" href="/"><img src="{% static 'img/logo-main.png' %}" width="50%" alt="logo" /></a> 
						</div>

						<div class="col-md-8 d-none d-md-block">
							<!-- social icons -->
							<ul class="social-icons list-unstyled list-inline mb-0 float-end">
								<li class="list-inline-item"><a href="https://www.facebook.com/aicouncil.tj"><i class="fab fa-facebook-f"></i></a></li>
								<li class="list-inline-item"><a href="https://www.instagram.com/aiacademy.tj/"><i class="fab fa-instagram"></i></a></li>
								<li class="list-inline-item"><a href="https://t.me/aiacademytj"><i class="fab fa-telegram"></i></a></li>
							</ul>
						</div>

					</div>
				</div>
			</div>

			<nav class="navbar navbar-expand-lg">
				<!-- header bottom -->
				<div class="header-bottom  w-100">
					
					<div class="container-xl">
						<div class="d-flex align-items-center">
							<div class="collapse navbar-collapse flex-grow-1">
								<!-- menus -->
								<ul class="navbar-nav">
									<li class="nav-item dropdown active">
										<a class="nav-link" href="/">Главная</a>
									</li>
									<li class="nav-item">
										<a class="nav-link" href="about">Академия ИИ</a>
									</li>
									<li class="nav-item dropdown">
										<a class="nav-link dropdown" href="#">Курсы <i class="fa-solid fa-angle-down"></i></a>
										<ul class="dropdown-menu">
											<li><a class="dropdown-item" href="basiccourse">Basic Course</a></li>
											<li><a class="dropdown-item" href="dataanalytics">Data Analytics</a></li>
											<li><a class="dropdown-item" href="datascience">Data Science</a></li>
											<li><a class="dropdown-item" href="mlops">ML Ops</a></li>
										</ul>
									</li>
									<li class="nav-item">
										<a class="nav-link" href="/#events">Расписание</a>
									</li>
									<li class="nav-item">
										<a class="nav-link" href="/#testimonial">Отзывы</a>
									</li>
									<li class="nav-item">
										<a class="nav-link" href="blog">Блог</a>
									</li>
									<li class="nav-item">
										<a class="nav-link" href="/#faq">FAQ</a>
									</li>
									<li class="nav-item">
										<a class="nav-link" href="contact">Связаться с нами</a>
									</li>
								</ul>
							</div>

							<!-- header buttons -->
							<div class="header-buttons">
								<button class="categoryshe lg">
									<ul class="navbarchik">
										<li class="nav-item">
											<a class="nav-link" href="https://taplink.cc/aic.tj">Подать заявку</a>
										</li>
									</ul>
								</button>
								
								<button class="burger-menu icon-button ms-2 float-end float-lg-none">
									<span class="burger-icon"></span>
								</button>
							</div>
						</div>
					</div>

				</div>
			</nav>

	</header>



</div>

	</header>
  
{% block body %}{% endblock %}

<footer class="footer">
	<div class="container">
	  <div class="footer-top">
		<div class="row">
		  <!-- Логотип -->
		  <div class="col-lg-12 text-center mb-4">
			<a href="#" class="footer-logo">
			  <img src="{% static 'img/logo-white.png' %}" alt="Логотип компании">
			</a>
		  </div>
  
		  <!-- Контактная информация -->
		  <div class="col-lg-3 col-md-6 mb-4">
			<h4 class="footer-heading">Контактная информация</h4>
			<ul class="footer-contact">
			  <li><i class="fa fa-map-marker-alt"></i> г. Душанбе, улица Примерная, 12</li>
			  <li><i class="fa fa-phone"></i> +992 123 456 789</li>
			  <li><i class="fa fa-envelope"></i> info@example.com</li>
			</ul>
		  </div>
  
		  <!-- Социальные сети -->
		  <div class="col-lg-3 col-md-6 mb-4">
			<h4 class="footer-heading">Социальные сети</h4>
			<div class="footer-social">
				<a href="#" class="social-icon facebook" aria-label="Facebook"><i class="fab fa-facebook-f"></i></a>
				<a href="#" class="social-icon twitter" aria-label="Twitter"><i class="fab fa-twitter"></i></a>
				<a href="#" class="social-icon instagram" aria-label="Instagram"><i class="fab fa-instagram"></i></a>
				<a href="#" class="social-icon linkedin" aria-label="LinkedIn"><i class="fab fa-linkedin-in"></i></a>
			</div>
		  </div>
  
		  <!-- Полезные ссылки -->
		  <div class="col-lg-3 col-md-6 mb-4">
			<h4 class="footer-heading">Полезные ссылки</h4>
			<ul class="footer-links">
			  <li><a href="#">О нас</a></li>
			  <li><a href="#">Часто задаваемые вопросы</a></li>
			  <li><a href="#">Политика конфиденциальности</a></li>
			  <li><a href="#">Условия использования</a></li>
			</ul>
		  </div>
  
		  <!-- Подписка на новости -->
		  <div class="col-lg-3 col-md-6 mb-4">
			<h4 class="footer-heading">Подписка на новости</h4>
			<form class="footer-subscription">
			  <input type="email" placeholder="Ваш email" required>
			  <button type="submit" class="btn btn-primary">Подписаться</button>
			</form>
		  </div>
		</div>
	  </div>
  
	  <div class="footer-bottom">
		<p class="footer-copy">© 2024 Академия ИИ. Все права защищены. Разработано <a href="https://samizoda.netlify.app">samizoda' Inc.</a></p>
	  </div>
	</div>
  </footer>
  


<!-- canvas menu -->
<div class="canvas-menu d-flex align-items-end flex-column">
	<!-- close button -->
	<button type="button" class="btn-close" aria-label="Close"></button>

	<!-- logo -->
	<div class="logo">
		<img src="{% static 'img/logo-main.png' %}" alt="Katen" />
	</div>

	<!-- menu -->
	<nav>
		<ul class="vertical-menu">
			<li class="active"><a href="/">Главная</a></li>
			<li><a href="#">Академия ИИ</a></li>

			<li>
				<a href="#">Курсы</a>
				<ul class="submenu">
					<li><a href="basiccourse">Basic Course</a></li>
					<li><a href="dataanalytics">Data Analytics</a></li>
					<li><a href="datascience">Data Science</a></li>
					<li><a href="mlops">ML Ops</a></li>
				</ul>
			</li>
			<li><a href="#events">Расписание</a></li>
			<li><a href="#testimonial">Отзывы</a></li>
			<li><a href="blog">Блог</a></li>
			<li><a href="#faq">FAQ</a></li>
			<li><a href="contact">Связаться с нами</a></li>
		</ul>
	</nav>

	<!-- social icons -->
	<ul class="social-icons list-unstyled list-inline mb-0 mt-auto w-100">
		<li class="list-inline-item"><a href="https://www.facebook.com/aicouncil.tj"><i class="fab fa-facebook-f"></i></a></li>
		<li class="list-inline-item"><a href="https://www.instagram.com/aiacademy.tj/"><i class="fab fa-instagram"></i></a></li>
		<li class="list-inline-item"><a href="https://t.me/aiacademytj"><i class="fab fa-telegram"></i></a></li>

	</ul>
</div>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.min.js'%}"></script>
<script src="{% static 'js/bootstrap.min.js'%}"></script>
<script src="{% static 'js/slick.min.js'%}"></script>
<script src="{% static 'js/jquery.sticky-sidebar.min.js'%}"></script>
<script src="{% static 'js/custom.js'%}"></script>
<script>
  document.addEventListener("DOMContentLoaded", function () {
      const burgerMenuButton = document.querySelector(".burger-menu");
      const canvasMenu = document.querySelector(".canvas-menu");
      const closeButton = document.querySelector(".canvas-menu .btn-close");

      burgerMenuButton.addEventListener("click", function () {
          canvasMenu.classList.add("open");
      });

      closeButton.addEventListener("click", function () {
          canvasMenu.classList.remove("open");
      });
  });
</script>


</body>
</html>

templates/pagination.html
<div class="row mt-5 mb-3 justify-content-center">
  <p class="text-center">Страница {{ blogs.number }} - {{ blogs.paginator.num_pages }}</p>
</div>
<div class="row">
  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
      {% if blogs.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?{% if query %}query={{query}}&{% endif %}page={{ blogs.previous_page_number }}" aria-label="Предыдущий">
            <i class="bi bi-caret-left"></i>
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <i class="page-link bi bi-caret-left"></i>
        </li>
      {% endif %}
      {% for i in blogs.paginator.page_range %}
        {% if blogs.number == i %}
          <li class="page-item active" aria-current="page">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?{% if query %}query={{query}}&{% endif %}page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if blogs.has_next %}
        <li class="page-item">
          <a class="page-link" href="?{% if query %}query={{query}}&{% endif %}page={{ blogs.next_page_number }}" aria-label="Следующий">
            <i class="bi bi-caret-right"></i>
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <i class="page-link bi bi-caret-right"></i>
        </li>
      {% endif %}
    </ul>
  </nav>
</div>

templates/popular.html
{% extends 'layout.html' %}

{% block title %}Популярный{% endblock %}

{% block body %}
<div class="container" style="margin-top: 100px;">
  <div class="row mb-1">
    <h2 style="text-align: center;"><b>Популярные посты</b></h2>
    <div class="col-6">



    </div>

  </div>
  <div class="row row-cols-1 row-cols-md-3 g-4 mt-1">
    {% for blog in blogs %}
      {% include 'card.html' with blog=blog %}
    {% endfor %}
  </div>
  {% include 'pagination.html' with blogs=blogs %}
</div>
{% endblock %}

templates/search.html
{% extends 'layout.html' %}

{% block title %}{{ query }} - Поиск {% endblock %}

{% block body %}
<div class="container" style="margin-top: 80px; margin-bottom: 50px;">
  <div class="row">
    <h3>Результаты поиска по запросу "{{ query }}"</h3>
  </div>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for blog in blogs %}
      {% include 'card.html' with blog=blog %}
    {% empty %}
    <p class="mt-5">Данные не найдены !!!<p>
    {% endfor %}
  </div>
  {% include 'pagination.html' with blogs=blogs %}
</div>
{% endblock %}

templates/trendings.html
{% extends 'layout.html' %}

{% block title %}В тренде{% endblock %}

{% block body %}
<div class="container" style="margin-top: 100px;">
  <div class="row mb-1">
    <h2 style="text-align: center;"><b>Новости в тренде</b></h2>
    <div class="col-6">



    </div>

  </div>
  <div class="row row-cols-1 row-cols-md-3 g-4 mt-1">
    {% for blog in blogs %}
      {% include 'card.html' with blog=blog %}
    {% endfor %}
  </div>
  {% include 'pagination.html' with blogs=blogs %}
</div>
{% endblock %}